version: '3.8'

services:
    webserv:
        container_name: our-prod-nginx
        image: our-nginx-image
        build:
            context: ./nginx/
        ports:
            - '80:80'
        volumes:
            - ./frontend/dist/:/var/www/cosmic-pong
        networks:
            - prod-appnet

    postgres:
        container_name: our-prod-postgresql
        image: postgres:latest
        volumes:
            - prod-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        networks:
            - prod-appnet

    backend:
        container_name: our-prod-backend
        image: node:18-alpine
        working_dir: /app
        ports:
            - '8080:3000'
        volumes:
            - ./backend:/app
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - PORT=${PORT}
            - FT_UUID=${FT_UUID}
            - FT_SECRET=${FT_SECRET}
            - URL_BACKEND=http://localhost
            - URL_FRONTEND=http://localhost
        depends_on:
            - postgres
        networks:
            - prod-appnet
        command: node /app/dist/main

volumes:
    prod-data:
      name: our-prod-volume

networks:
    prod-appnet:
