version: '3.8'
services:
    backend:
        build:
            context: ./backend/nest/
        ports:
            - '8080:3000'
        volumes:
            - ./backend/nest:/app/src:delegated
            - /app/node_modules
        depends_on:
            - postgres
        env_file:
            - ./env/nest.env
        networks:
            - appnet

    frontend:
        build:
            context: ./frontend/react/
        ports:
            - '4040:5173'
        volumes:
            - ./frontend/react:/app
            - /app/node_modules
        stdin_open: true
        tty: true

    postgres:
        image: postgres:latest
        ports:
            - '6060:5432'
        volumes:
            - data:/var/lib/postgresql/data
        env_file:
            - './env/postgres.env'
        networks:
            - appnet

volumes:
    data:
networks:
    appnet:
