Table Player {
    id int [pk]
    login text
    avatarUrl text
    nbVictory int
    totalPlay int
    xp int
    TFASecret varchar
    TFAEnabled boolean
    FT_id varchar
}

Table Friends {
    id int [pk]
    player int
    friend int
    isPending boolean
}

Table Match {
    id int [pk]
    playerHome int
    playerForeign int
    Winner int
    HomeScore int
    ForeignScore int
    creationDate date
}

Table player_channels_channel {
    user int
    channel int
}

Table Channel {
    id int [pk]
    owner int
    name varchar(500)
    type varchar
    password varchar
    creationDate date
}

Ref: Player.id < Friends.player
Ref: Player.id < Friends.friend

Ref: Player.id < Match.playerHome
Ref: Player.id < Match.playerForeign
Ref: Player.id < Match.Winner

Ref: Player.id < player_channels_channel.user

Ref: player_channels_channel.channel > Channel.id
